version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: bash -c "gunicorn app.wsgi:application -b 0:8000"
    volumes:
      - ./app:/app